read_matlab_outputs = function(filepath){
  
  #'
  #' @title import strat columns from CarboCAT
  #' 
  #' @param filepath filepath to the matlab file
  #' 
  #' @returns a list of stratigraphic columns, each consisting of positon, bed thickness, and facies
  #' 
  #' @details
    #' reads .mat files storing variables generated by "get_strat_columns" from the CarboCAT_utils repo.
    #' 
  
  data = R.matlab::readMat(filepath)
  
  x_positions = data[[1]][[1]][1,]
  y_positions = data[[1]][[2]][1,]
  
  thicknesses = data[[1]][[3]]
  facies = data[[1]][[4]]
  
  strat_cols = list()
  
  for ( i in seq_along(x_positions)){
    strat_cols[[i]] = list("x_pos" = x_positions[i],
                           "y_pos" = y_positions[i],
                           "thickness" = thicknesses[[i]][[1]][1,],
                           "facies" = facies[[i]][[1]][1,])
  }
  
  return(strat_cols)
  
}



